version: '3.7'

services:
  db:
    image: postgres:12
    environment:
      - POSTGRES_DB=express_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin2021
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - POSTGRES_DB=express_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin2021
      - POSTGRES_HOST=db
